production_bucket: vo_agam_production
temp_bucket: vo_anoph_temp_us_central1
temp_bucket_subpath: vo_agam
staging_bucket: vo_agam_staging
release_bucket: vo_agam_release
release_master_bucket: vo_agam_release_master_us_central1
major_version: 3
major_version_string: 'v3'
latest_minor_version: 12
contigs: ['X', '2R', '2L', '3R', '3L']
contamination_contigs: ['3R', '3L']
allsites_zip_path: vo_agam_production/resources/observatory/ag.allsites.nonN.zarr.zip
allele_freqs_path: vo_agam_production/resources/observatory/phase2_biallelic_variantsites_af.zarr
sex_call_divisor_contig: '3R'
provisional_accessibility_path: ag1000g-release/phase2.AR1/accessibility/accessibility.zarr
provisional_accessibility_field: is_accessible
provisional_accessibility_ref_n_field: ref_n
PCA_regions: [
    ['3L', 1, 41_963_435]
]
PCA_accessibility_path: vo_agam_production/resources/observatory/non_n_accessibility/non_n_accessibility.zarr
PCA_accessibility_field: is_accessible
API_class_name: 'Ag3'
include_AIMs: true
AIMs_analysis: '20220528'
AIM_definitions_dir_path: vo_agam_release/reference/aim_defs_20220528
AIM_definition_contigs: ['2R', '2L', '3R', '3L', 'X']
AIM_site_filter_masks: ['gamb_colu_arab', 'gamb_colu', 'arab']
AIM_site_filter_masks_dir_path: vo_agam_release/v3/site_filters/dt_20200416
AIM_allsites_path: vo_agam_release/v3/snp_genotypes/all/sites
AIM_call_groups: ['gambcolu_vs_arab', 'gamb_vs_colu']
AIM_call_group_variant_counts: # TODO: where can these numbers be sourced from?
    gambcolu_vs_arab: 2612
    gamb_vs_colu: 700
AIM_call_group_fraction_names:
    gambcolu_vs_arab: arab
    gamb_vs_colu: colu
AIM_fraction_class_ranges:
    arab:
        arabiensis: [0.85, 1]
        gambcolu: [0, 0.1]
    colu:
        coluzzii: [0.9, 1]
        gambiae: [0, 0.1]
AIM_species_calls_column_names: ['aim_species_gambcolu_arabiensis', 'aim_species_gambiae_coluzzii', 'aim_species'] # This needs to match the order returned by call_aim_species() in produce_AIM_species_calls.ipynb
AIM_species_calls_columns_with_missingness: ['aim_species_gambiae_coluzzii']
AIM_exclusion_call_group: 'gamb_vs_colu'
AIM_exclusion_contig: '2L'
prov_taxa_classifier_set: 'RF_20231019'
cohorts_analysis: '20240717'
reference_samples_analysis: 'ref_samples_20240717'
temp_subpath: vo_agam_temp
CNV_VCF_reference_URL: https://storage.googleapis.com/vo_agam_release/reference/genome/agamp4/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa.gz
CNV_HMM_contig_variant_counts: # TODO: where can these numbers be sourced from?
    2L: 164548
    2R: 205151
    3L: 139879
    3R: 177336
    X: 81311
CNV_coverage_species_groups: ['gambcolu', 'arabiensis']
CNV_coverage_VCF_species_group_translations:
    arab: arabiensis
    gamb_colu: gambcolu
CNV_target_regions_analysis_subpath: target_regions_analysis_230911
CNV_target_regions_analysis: 20230911
CNV_DRC_contigs: ['X', '2R', '2L', '3R']
CNV_DRC_contig_variant_counts: # TODO: where can these numbers be sourced from?
    2R: 47
    3R: 29
    X: 29
    2L: 22
